# Generated by Django 2.2.3 on 2019-07-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20190721_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
