# Generated by Django 2.2.3 on 2019-07-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_course_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='required',
            new_name='recommended',
        ),
    ]
